### ISSUE TITLE
compilation on beta environment deployment fails due to connection timeout

### ISSUE THREAD

**Issue by ipolyzos** [starkandwayne/codex#98]
following codex steps, the beta environment deployment phase in the package compilation phase due to timeout i.e.

> Started compiling packages
>  Started compiling packages > registry/02be563161fd57b6a9a3a0e2c572ea310bd9085f
>  Started compiling packages > ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042
>   Failed compiling packages > registry/02be563161fd57b6a9a3a0e2c572ea310bd9085f: Timed out pinging to 478be71d-f8ac-4ddf-927a-35a0efaa4bcf after 600 seconds (00:11:06)
 >  Failed compiling packages > ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042: >Timed out pinging to 3abbc9a7-1995-4456-b4f5-794984675919 after 600 seconds (00:11:07)
>
>Error 450002: Timed out pinging to 478be71d-f8ac-4ddf-927a-35a0efaa4bcf after 600 seconds

you could also refer the bosh logs below

>D, [2017-03-12T21:11:25.212451 #20632] DEBUG -- : Waiting for i-0eb081ca36bd5d11c to be terminated, retrying in 2 seconds (1/54)                       [94/1848]
>I, [2017-03-12T21:11:27.459296 #20632]  INFO -- : [AWS EC2 200 0.245528 0 retries] describe_instances(:instance_ids=>["i-0eb081ca36bd5d11c"])
>
>D, [2017-03-12T21:11:27.460350 #20632] DEBUG -- : Waiting for i-0eb081ca36bd5d11c to be terminated, retrying in 4 seconds (2/54)
>I, [2017-03-12T21:11:31.610469 #20632]  INFO -- : [AWS EC2 200 0.148997 0 retries] describe_instances(:instance_ids=>["i-0eb081ca36bd5d11c"])
>
>D, [2017-03-12T21:11:31.611467 #20632] DEBUG -- : Waiting for i-0eb081ca36bd5d11c to be terminated, retrying in 8 seconds (3/54)
>I, [2017-03-12T21:11:39.717124 #20632]  INFO -- : [AWS EC2 200 0.104579 0 retries] describe_instances(:instance_ids=>["i-0eb081ca36bd5d11c"])
>
>D, [2017-03-12T21:11:39.718153 #20632] DEBUG -- : Waiting for i-0eb081ca36bd5d11c to be terminated, retrying in 16 seconds (4/54)
>I, [2017-03-12T21:11:55.827086 #20632]  INFO -- : [AWS EC2 200 0.107907 0 retries] describe_instances(:instance_ids=>["i-0eb081ca36bd5d11c"])
>
>I, [2017-03-12T21:11:55.828119 #20632]  INFO -- : i-0eb081ca36bd5d11c is now terminated, took 30.709345461s
>, exit_status: pid 20632 exit 0
>D, [2017-03-12 21:11:55 #20389] [compile_package(ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.12)] DEBUG
>-- DirectorJobRunner: (0.000144s) SELECT NULL
>D, [2017-03-12 21:11:55 #20389] [compile_package(ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.12)] DEBUG
>-- DirectorJobRunner: (0.000111s) SELECT NULL
>D, [2017-03-12 21:11:55 #20389] [compile_package(ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.12)] DEBUG
>-- DirectorJobRunner: (0.000589s) SELECT count(*) AS "count" FROM "instances" WHERE (("deployment_id" = 6) AND ("job" = 'compilation-872150fc-f37e-431a-af91-7bf
>054a0ea42') AND ("index" = 0) AND ("id" != 43)) LIMIT 1
>D, [2017-03-12 21:11:55 #20389] [compile_package(ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.12)] DEBUG
>-- DirectorJobRunner: (0.000112s) SELECT NULL
>D, [2017-03-12 21:11:55 #20389] [compile_package(ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.12)] DEBUG
>-- DirectorJobRunner: (0.000067s) BEGIN
>D, [2017-03-12 21:11:55 #20389] [compile_package(ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.12)] DEBUG
>-- DirectorJobRunner: (0.000360s) UPDATE "instances" SET "vm_cid" = NULL, "agent_id" = NULL, "credentials_json" = 'null', "trusted_certs_sha1" = NULL WHERE ("id
>" = 43)
>D, [2017-03-12 21:11:55 #20389] [compile_package(ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.12)] DEBUG
>-- DirectorJobRunner: (0.003974s) COMMIT
>D, [2017-03-12 21:11:55 #20389] [compile_package(ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.12)] DEBUG
>-- DirectorJobRunner: [network-configuration] Deleting ip '10.10.32.6' for default
>D, [2017-03-12 21:11:55 #20389] [compile_package(ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.12)] DEBUG
>-- DirectorJobRunner: (0.000121s) SELECT NULL
>D, [2017-03-12 21:11:55 #20389] [compile_package(ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.12)] DEBUG
>-- DirectorJobRunner: (0.000069s) BEGIN
>D, [2017-03-12 21:11:55 #20389] [compile_package(ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.12)] DEBUG
>-- DirectorJobRunner: (0.000300s) SELECT * FROM "ip_addresses" WHERE ("ip_addresses"."instance_id" = 43)
>D, [2017-03-12 21:11:55 #20389] [compile_package(ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.12)] DEBUG
>-- DirectorJobRunner: (0.000250s) DELETE FROM "instances_templates" WHERE ("instance_id" = 43)
>D, [2017-03-12 21:11:55 #20389] [compile_package(ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.12)] DEBUG
>-- DirectorJobRunner: (0.001408s) DELETE FROM "instances" WHERE "id" = 43
>D, [2017-03-12 21:11:55 #20389] [compile_package(ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.12)] DEBUG
>-- DirectorJobRunner: (0.000963s) COMMIT
>D, [2017-03-12 21:11:55 #20389] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
>D, [2017-03-12 21:11:55 #20389] [compile_package(ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.12)] DEBUG
>-- DirectorJobRunner: (0.000121s) SELECT NULL
>D, [2017-03-12 21:11:55 #20389] [compile_package(ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042, bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3363.12)] DEBUG
>-- DirectorJobRunner: (0.000102s) SELECT NULL
>D, [2017-03-12 21:11:55 #20389] [task:49] DEBUG -- DirectorJobRunner: (0.001027s) DELETE FROM "locks" WHERE (("name" = 'lock:deployment:us-east-1-staging-bosh') AND ("uid" = '82b3e8d8-f54b-4418-b80b-ed0f3eaf7cf7'))
>D, [2017-03-12 21:11:55 #20389] [task:49] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:us-east-1-staging-bosh uid: 82b3e8d8-f54b-4418-b80b-ed0f3eaf7cf7
>I, [2017-03-12 21:11:55 #20389] [task:49]  INFO -- DirectorJobRunner: sending update deployment error event
>D, [2017-03-12 21:11:55 #20389] [task:49] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"0099bf27-5fc4-475f-ab31-b2b0ac726bed","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for 'us-east-1-staging-bosh' against Director 'f23d345f-56ba-440b-b446-b0597e5c3b80': #<Bosh::Director::RpcTimeout: Timed out pinging to a6f6f407-5e8a-44dc-80d3-a2d3607b087b after 600 seconds>","created_at":1489353115}
>E, [2017-03-12 21:11:55 #20389] [task:49] ERROR -- DirectorJobRunner: Timed out pinging to a6f6f407-5e8a-44dc-80d3-a2d3607b087b after 600 seconds
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/agent_client.rb:187:in `rescue in wait_until_ready'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/agent_client.rb:193:in `wait_until_ready'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/vm_creator.rb:66:in `create_for_instance_plan'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:144:in `create_instance'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:185:in `instance'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:16:in `with_reused_vm'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:115:in `prepare_vm'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:66:in `block in compile_package'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/lock_helper.rb:48:in `block in with_compile_lock'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/lock.rb:53:in `lock'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/lock_helper.rb:48:in `with_compile_lock'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:59:in `compile_package'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:204:in `block (2 levels) in process_task'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:202:in `block in process_task'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:198:in `process_task'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.0.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:162:in `block (4 levels) in compile_packages'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_pool.rb:63:in `loop'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-260.0.0/lib/common/thread_pool.rb:63:in `block in create_thread'
>/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
>D, [2017-03-12 21:11:55 #20389] [task:49] DEBUG -- DirectorJobRunner: (0.000111s) SELECT NULL
>D, [2017-03-12 21:11:55 #20389] [task:49] DEBUG -- DirectorJobRunner: (0.000081s) BEGIN
>D, [2017-03-12 21:11:55 #20389] [task:49] DEBUG -- DirectorJobRunner: (0.000267s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2017-03-12 21:11:55.913681+0000', "description" = 'create deployment', "result" = 'Timed out pinging to a6f6f407-5e8a-44dc-80d3-a2d3607b087b after 600 seconds', "output" = '/var/vcap/store/director/tasks/49', "checkpoint_time" = '2017-03-12 21:00:49.613911+0000', "type" = 'update_deployment', "username" = 'admin', "deployment_name" = 'us-east-1-staging-bosh', "started_at" = '2017-03-12 21:00:49.613842+0000' WHERE ("id" = 49)
>D, [2017-03-12 21:11:55 #20389] [task:49] DEBUG -- DirectorJobRunner: (0.001016s) COMMIT
>I, [2017-03-12 21:11:55 #20389] []  INFO -- DirectorJobRunner: Task took 11 minutes 6.304526239999973 seconds to process.
>
>Task 49 error

is there any further networking configuration or ACL changes that might be needed?

**Comment by ipolyzos** [comment]
some ports missing from the ACL, opening access to all ports temporarily resolves the issue

**Comment by ipolyzos** [comment]
opening access like wide-open group solves the problem, need to dig more into the ports missing from ACLs
